### ISSUE TITLE
Hostsystem not yet shown

### ISSUE THREAD

**Issue by miit0o** [emernet-eins/system#24]
Host system not yet shown in about page.

Maybe a future feature, but why not do it in 1.0?

**Comment by CodeF0x** [comment]
@miit0o Oh no, I totally forgot about this. I think we need some sort meeting like Discord or something, as I would need some backend help for this.

**Comment by CodeF0x** [comment]
Discussed [here](https://github.com/emernet-eins/server/issues/6) and implemented in #25
